version: "3.4"

services:

  drupal:
    image: drupal:8-apache
    ports:
      - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    restart: unless-stopped

  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: password
    restart: unless-stopped
